import React, { useMemo, useState, useEffect } from "react";
import "./AddStudentModal.css";

const YEAR_LEVELS = [
  { value: "1", label: "1st Year" },
  { value: "2", label: "2nd Year" },
  { value: "3", label: "3rd Year" },
  { value: "4", label: "4th Year" },
];

const SECTIONS = ["A", "B", "C"];

function buildPasswordFromSurname(surname) {
  return (surname || "").trim().replace(/\s+/g, "").toUpperCase();
}

export default function AddStudentModal({ open, onClose, onSubmit }) {
  const [firstName, setFirstName] = useState("");
  const [middleName, setMiddleName] = useState("");
  const [surname, setSurname] = useState("");
  const [suffix, setSuffix] = useState("");

  const [studentId, setStudentId] = useState("");
  const [yearLevel, setYearLevel] = useState("");
  const [section, setSection] = useState("");
  const [password, setPassword] = useState("");

  useEffect(() => {
    setPassword(buildPasswordFromSurname(surname));
  }, [surname]);

  const errors = useMemo(() => {
    const e = {};
    if (!firstName.trim()) e.firstName = "Required";
    if (!surname.trim()) e.surname = "Required";
    if (!studentId.trim()) e.studentId = "Required";
    if (!yearLevel) e.yearLevel = "Required";
    if (!section) e.section = "Required";
    return e;
  }, [firstName, surname, studentId, yearLevel, section]);

  const canSubmit = Object.keys(errors).length === 0;

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!canSubmit) return;

    onSubmit?.({
      name: {
        firstName,
        middleName,
        surname,
        suffix,
        fullName: [firstName, middleName, surname, suffix]
          .filter(Boolean)
          .join(" "),
      },
      studentId,
      yearLevel,
      section,
      classSection: `${yearLevel}${section}`,
      password,
    });

    onClose?.();
  };

  if (!open) return null;

  return (
    <div className="asm-overlay" onMouseDown={onClose}>
      <div className="asm-modal" onMouseDown={(e) => e.stopPropagation()}>
        <div className="asm-title">Add New Student</div>

        <form className="asm-form" onSubmit={handleSubmit}>
          <label className="asm-label">
            First Name <span className="asm-req">*</span>
          </label>
          <input
            className={`asm-input ${errors.firstName ? "err" : ""}`}
            value={firstName}
            onChange={(e) => setFirstName(e.target.value)}
          />

          <label className="asm-label">Middle Name</label>
          <input
            className="asm-input"
            value={middleName}
            onChange={(e) => setMiddleName(e.target.value)}
          />

          <label className="asm-label">
            Surname <span className="asm-req">*</span>
          </label>
          <input
            className={`asm-input ${errors.surname ? "err" : ""}`}
            value={surname}
            onChange={(e) => setSurname(e.target.value)}
          />

          <label className="asm-label">Suffix</label>
          <input
            className="asm-input"
            value={suffix}
            onChange={(e) => setSuffix(e.target.value)}
          />

          <label className="asm-label">
            Student ID <span className="asm-req">*</span>
          </label>
          <input
            className={`asm-input ${errors.studentId ? "err" : ""}`}
            value={studentId}
            onChange={(e) => setStudentId(e.target.value)}
          />

          <label className="asm-label">
            Year Level <span className="asm-req">*</span>
          </label>
          <select
            className={`asm-input asm-select ${errors.yearLevel ? "err" : ""}`}
            value={yearLevel}
            onChange={(e) => setYearLevel(e.target.value)}
          >
            <option value="">Select Year</option>
            {YEAR_LEVELS.map((y) => (
              <option key={y.value} value={y.value}>
                {y.label}
              </option>
            ))}
          </select>

          <label className="asm-label">
            Section <span className="asm-req">*</span>
          </label>
          <select
            className={`asm-input asm-select ${errors.section ? "err" : ""}`}
            value={section}
            onChange={(e) => setSection(e.target.value)}
          >
            <option value="">Select Section</option>
            {SECTIONS.map((s) => (
              <option key={s}>{s}</option>
            ))}
          </select>

          <label className="asm-label">Password</label>
          <input
            className="asm-input asm-disabledPass"
            value={password}
            placeholder="Generated by surname"
            disabled
          />
          <div className="asm-hint">Password is generated by surname</div>

          <div className="asm-actions">
            <button className="asm-btn primary" disabled={!canSubmit}>
              Add
            </button>
            <button className="asm-btn" type="button" onClick={onClose}>
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
